// Auto-generated by scripts/generate-example-images.ts — do not edit.
export const EXAMPLE_IMAGES = [
  {
    "id": "image1",
    "fileName": "image1.webp",
    "src": "/examples/image1.webp"
  },
  {
    "id": "image2",
    "fileName": "image2.webp",
    "src": "/examples/image2.webp"
  },
  {
    "id": "image3",
    "fileName": "image3.webp",
    "src": "/examples/image3.webp"
  },
  {
    "id": "image4",
    "fileName": "image4.webp",
    "src": "/examples/image4.webp"
  },
  {
    "id": "image5",
    "fileName": "image5.webp",
    "src": "/examples/image5.webp"
  },
  {
    "id": "image6",
    "fileName": "image6.webp",
    "src": "/examples/image6.webp"
  },
  {
    "id": "image7",
    "fileName": "image7.webp",
    "src": "/examples/image7.webp"
  },
  {
    "id": "image8",
    "fileName": "image8.webp",
    "src": "/examples/image8.webp"
  }
] as const;

export type ExampleImage = (typeof EXAMPLE_IMAGES)[number];
export type ExampleImageId = ExampleImage["id"];
