// Auto-generated by scripts/generate-example-images.ts — do not edit.
export const EXAMPLE_IMAGES = [
  {
    "id": "image1",
    "fileName": "image1.webp",
    "src": "/examples/image1.webp"
  },
  {
    "id": "image2",
    "fileName": "image2.webp",
    "src": "/examples/image2.webp"
  },
  {
    "id": "image3",
    "fileName": "image3.webp",
    "src": "/examples/image3.webp"
  },
  {
    "id": "image4",
    "fileName": "image4.webp",
    "src": "/examples/image4.webp"
  },
  {
    "id": "image5",
    "fileName": "image5.webp",
    "src": "/examples/image5.webp"
  },
  {
    "id": "image6",
    "fileName": "image6.webp",
    "src": "/examples/image6.webp"
  },
  {
    "id": "image7",
    "fileName": "image7.webp",
    "src": "/examples/image7.webp"
  },
  {
    "id": "image8",
    "fileName": "image8.webp",
    "src": "/examples/image8.webp"
  },
  {
    "id": "image9",
    "fileName": "image9.webp",
    "src": "/examples/image9.webp"
  },
  {
    "id": "image10",
    "fileName": "image10.webp",
    "src": "/examples/image10.webp"
  },
  {
    "id": "image11",
    "fileName": "image11.webp",
    "src": "/examples/image11.webp"
  },
  {
    "id": "image12",
    "fileName": "image12.webp",
    "src": "/examples/image12.webp"
  },
  {
    "id": "image13",
    "fileName": "image13.webp",
    "src": "/examples/image13.webp"
  },
  {
    "id": "image14",
    "fileName": "image14.webp",
    "src": "/examples/image14.webp"
  },
  {
    "id": "image15",
    "fileName": "image15.webp",
    "src": "/examples/image15.webp"
  },
  {
    "id": "image16",
    "fileName": "image16.webp",
    "src": "/examples/image16.webp"
  },
  {
    "id": "image17",
    "fileName": "image17.webp",
    "src": "/examples/image17.webp"
  },
  {
    "id": "image18",
    "fileName": "image18.webp",
    "src": "/examples/image18.webp"
  }
] as const;

export type ExampleImage = (typeof EXAMPLE_IMAGES)[number];
export type ExampleImageId = ExampleImage["id"];
