import type { Language } from "@/lib/language";

/** Typographic brand OG images — generated by `npm run generate-share-assets`. */
export const SHARE_HEADER_IMAGES = {
  dark: {
    en: "/share-pix-8-dark-en.png",
    he: "/share-pix-8-dark-he.png",
  },
  light: {
    en: "/share-pix-8-light-en.png",
    he: "/share-pix-8-light-he.png",
  },
} as const satisfies Record<"dark" | "light", Record<Language, string>>;

export const DEFAULT_SHARE_IMAGE = SHARE_HEADER_IMAGES.dark.en;

export function getShareHeaderImage(
  language: Language,
  isDark: boolean,
): string {
  return SHARE_HEADER_IMAGES[isDark ? "dark" : "light"][language];
}

export function resolveShareImageUrl(path: string, origin: string): string {
  return new URL(path, origin).href;
}

export type ShareTheme = "dark" | "light";

export function getShareTheme(isDark: boolean): ShareTheme {
  return isDark ? "dark" : "light";
}

/** URL params read by Cloudflare middleware for Facebook / other crawlers. */
export function withShareParams(
  url: URL,
  language: Language,
  theme: ShareTheme,
): URL {
  const next = new URL(url.href);
  next.searchParams.set("lang", language);
  next.searchParams.set("theme", theme);
  return next;
}

export function buildShareablePageUrl(
  href: string,
  language: Language,
  theme: ShareTheme,
): string {
  return withShareParams(new URL(href), language, theme).href;
}
