import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const EXAMPLES_DIR = join(process.cwd(), "public", "examples");
const OUTPUT_FILE = join(process.cwd(), "src", "lib", "exampleImages.generated.ts");

const IMAGE_FILE_PATTERN = /\.(webp|png|jpe?g|gif|avif)$/i;

export function generateExampleImages(): string {
  const files = readdirSync(EXAMPLES_DIR, { withFileTypes: true })
    .filter((entry) => entry.isFile() && IMAGE_FILE_PATTERN.test(entry.name))
    .map((entry) => entry.name)
    .sort((left, right) =>
      left.localeCompare(right, undefined, { numeric: true, sensitivity: "base" }),
    );

  const images = files.map((fileName) => {
    const id = fileName.replace(/\.[^.]+$/, "");
    return {
      id,
      fileName,
      src: `/examples/${fileName}`,
    };
  });

  const source = `// Auto-generated by scripts/generate-example-images.ts — do not edit.
export const EXAMPLE_IMAGES = ${JSON.stringify(images, null, 2)} as const;

export type ExampleImage = (typeof EXAMPLE_IMAGES)[number];
export type ExampleImageId = ExampleImage["id"];
`;

  writeFileSync(OUTPUT_FILE, source, "utf8");
  return OUTPUT_FILE;
}
